replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: gcr.io/core-workshop/cloudbees-days/smee-io
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.5"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # Ingress class to use for OC and MM ingresses
  # Should be set to the same value as nginx-ingress.controller.ingressClass if enabled
  class: nginx
  # Annotations to put on Ingress object
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: smee.local
  tls:
    secretName: smee-tls


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
