{{- if .Values.ingress.enabled -}}
{{- $fullName := include "smee-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hostname  := .Values.ingress.host -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "smee-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ $hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ $fullName }}
                port: {{ $svcPort }}
  {{- end }}
